"""empty message

Revision ID: 2f7deac7cdf1
Revises: 
Create Date: 2024-04-06 08:50:01.187341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7deac7cdf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    with op.batch_alter_table('anonyuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Enum('baby', 'child', 'adult', 'old', name='age_class'), nullable=True))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonyuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=True))
        batch_op.drop_column('age')

    op.create_table('videos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('other_names', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_videos'),
    sa.UniqueConstraint('url', name='uq_videos_url')
    )
    # ### end Alembic commands ###
